export const productConstants = {
   
    GETALLPRODUCTS_REQUEST: 'PRODUCTS_GETALL_REQUEST',
    GETALLPRODUCTS_SUCCESS: 'PRODUCTS_GETALL_SUCCESS',
    GETALLPRODUCTS_FAILURE: 'PRODUCTS_GETALL_FAILURE',
    POSTPRODUCT_REQUEST: 'PRODUCT_POST_REQUEST',
    POSTPRODUCT_SUCCESS: 'PRODUCT_POST_SUCCESS',
    POSTPRODUCT_FAILURE: 'PRODUCT_POST_FAILURE',

    DELETE_PRODUCT_SUCCESS: 'PRODUCT_DELETE_SUCCESS',
    PUT_PRODUCT_SUCCESS: 'PRODUCT_PUT_SUCCESS',
    TOGGLE_ADDPRODUCT: 'TOGGLE_DISPLAY'
};
